config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  get 'home/about' => 'homes#about'
  get 'search' => 'search#search'

  devise_for :users

  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:index, :create, :destroy]
    get 'follows', 'followers'
  end
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  get '*anything' => 'homes#top'

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController


 def create
    @book = Book.find(params[:book_id])
    @class = ".favorite-btn-#{@book.id}"
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    # redirect_back(fallback_location: root_path)
  end

  def destroy
    @book = Book.find(params[:book_id])
    @class = ".favorite-btn-#{@book.id}"
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    # redirect_back(fallback_location: root_path)
  end

  # def set_variables
  #   @book = Book.find(params[:book_id])
  #   @class = "favorite-btn-#{@book.id}"
  #   @book_id = ".favorite-btn-#{@book.id}"
  # end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite-btn.html.erb
<% if book.favorited_by?(current_user) %>

    <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
      <p>♥<%= book.favorites.count %> いいね</p>
    <% end %>

  <% else %>

    <%= link_to book_favorites_path(book), method: :post, remote: true do %>
      <P>♡<%= book.favorites.count %> いいね</P>
    <% end %>

<% end %>

app/views/favorites/create.js.erb
$("<%= @class %>").html("<%= escape_javascript(render partial: 'favorites/favorite-btn', locals: {book: @book}) %>");

app/views/favorites/destroy.js.erb
$("<%= @class %>").html("<%= escape_javascript(render partial: 'favorites/favorite-btn', locals: {book: @book}) %>");