config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  get 'home/about' => 'homes#about'
  get 'search' => 'search#search'

  devise_for :users

  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:index, :create, :destroy]
    get 'follows', 'followers'
  end
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  get '*anything' => 'homes#top'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy

  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  attachment :profile_image, destroy: false

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, presence: true, on: :update
  validates :introduction, length: { maximum: 50 } # 質問


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @on_favorites = false
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def follows
    @user = User.find(params[:user_id])
    @book = Book.new
  end

  def followers
    @user = User.find(params[:user_id])
    @book = Book.new
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th>follows</th>
      <th>followers</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= user.follower.count %></td>
        <td><%= user.followed.count %></td>
        <% if user.followed.pluck(:follower_id).include?(current_user.id) %>
          <td><%= link_to 'フォローを外す', user_relationships_path(user), method: :delete %></td>
        <% elsif user != current_user %>
          <td><%= link_to 'フォローをする', user_relationships_path(user), method: :post %></td>
        <% else %>
          <td><!--ただの空白--></td>
        <% end %>

        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
	  <th><%= link_to 'follows', user_follows_path(user) %></th>
	  <th><%= user.follower.count %></th>
  </tr>
  <tr>
	  <th><%= link_to 'followers', user_followers_path(user) %></th>
	  <th><%= user.followed.count %></th>
  </tr>

  <% unless user == current_user %>

  <tr>
	  <% if user.followed.pluck(:follower_id).include?(current_user.id) %>
      <th colspan="2"><%= link_to 'フォローを外す', user_relationships_path(user), class: "btn px-1 py-1 my-2 btn-success", method: :delete %></th>
    <% else %>
      <th colspan="2"><%= link_to 'フォローをする', user_relationships_path(user), class: "btn px-1 py-1 my-2 btn-info", method: :post %></th>
    <% end %>
  </tr>
  <% end %>
</table>

<div class='row'>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>

app/views/users/edit.html.erb
<div class='container px-5 px-sm-0'>
  <div class="col-md-6 mx-auto">

    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>

      <%= render 'layouts/errors', obj: @user %>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>

       <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>

      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>

      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>

    <% end %>

  </div> <!--<div class="col-md-8 mx-auto">の終わり-->
</div><!--<div class='container px-5 px-sm-0'>の終わり-->

app/views/users/followers.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>

    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>

      <table class='table followers_table'>
        <h2>followers</h2>
        <thead>
          <tr>
            <th>img</th>
            <th>name</th>
            <th>link</th>
          </tr>
        </thead>

        <tbody>
          <% users = @user.followed %>
          <% users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag(user.follower, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
            <td><%= user.follower.name %></td>
            <td><%= link_to 'Show', user_path(user.follower), class: "user_#{user.follower.id}" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/users/follows.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>

    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>

      <table class='table follows_table'>
        <h2>follows</h2>
        <thead>
          <tr>
            <th>img</th>
            <th>name</th>
            <th>link</th>
          </tr>
        </thead>

        <tbody>
          <% users = @user.follower %>
          <% users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag(user.followed, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
            <td><%= user.followed.name %></td>
            <td><%= link_to 'Show', user_path(user.followed), class: "user_#{user.followed.id}" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>

    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>

    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>

  </div>
</div>