config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  get 'home/about' => 'homes#about'
  get 'search' => 'search#search'

  devise_for :users

  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:index, :create, :destroy]
    get 'follows', 'followers'
  end
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  get '*anything' => 'homes#top'

end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy

	def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  # favoritesのデータベースに存在するuser_idカラムの各値が、
  # 引数として渡されたuserのidと一致するかどうかを調べてる。

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_book, only: [:update, :edit]

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @book_comment = BookComment.new
  end

  def index
    @books = Book.all
    @book = Book.new
    @on_favorites = true
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      flash[:alert] = 'メッセージを入力してください。'
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_book
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book_detailed_information.html.erb
<h2>Book detail</h2>
<table class='table'>
  <tr>

    <td><%= link_to user_path(book.user) do %>
      <%= attachment_image_tag(book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
      <%= book.user.name %>
      <% end %>
    </td>

    <td><%= link_to book.title, book_path(book) %></td>
    <td><%= book.body %></td>
    <td class="favorite-btn-<%= book.id %>"><%= render 'favorites/favorite-btn', book: book %></td>
    <td id="book_comments_count">コメント数：<%= book.book_comments.count %></td>

    <% if book.user == current_user %>
      <td><%= link_to 'Edit', edit_book_path(book), class: "btn btn-sm btn-success edit_book_#{book.id}" %></td>
      <td><%= link_to 'Destroy', book_path(book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{book.id}"%></td>
    <% end %>

  </tr>
</table>

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>

        <% if @on_favorites %>
          <td class="favorite-btn-<%= book.id %>"><%= render 'favorites/favorite-btn', book: book %></td>
        <% end %>

        <td><p>コメント数：<%= book.book_comments.count %></p></td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container px-5 px-sm-0'>
  <div class="col-md-6 mx-auto">
		<h1>Editing Book</h1>
  	<%= render 'layouts/errors', obj: @book %>
		<%= render 'form', book: @book %>
		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
		<%= link_to 'Back', books_path, class: "back" %>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>

  <!--errror.any?-->
  <%= render 'layouts/errors', obj: @book %>

  <div class='row'>

    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>

  </div>
</div>

app/views/books/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>

    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @new_book %>
    </div>

    <div class='col-md-8 offset-md-1'>

      <!--bookの詳細を表示する為のレンダー-->
      <div id="book_detaile">
        <%= render 'book_detailed_information', book: @book %>
      </div>

      <!--コメント一覧のレンダー-->
      <div id="comments_list" class="comments my-5">
        <%= render 'book_comments/book_comments_list', book: @book %>
      </div>

      <div class="new-comment">
        <div id="comments_field">
          <!--コメントフォームのレンダー-->
          <%= render 'book_comments/book_comments_field', {book: @book, book_comment: @book_comment} %>
        </div>
      </div>

    </div><!--<div class='col-md-8 offset-md-1'>の終わり-->

  </div><!--<div class='row'>の終わり-->
</div><!--<div class='container px-5 px-sm-0'>-->